### ISSUE TITLE
Another Running Error 

### ISSUE THREAD

**Issue by rafaelvectar** [ment4list/SublimeZilla#14]
I'm using Sublime Text 3 on Ubuntu 14.04 LTS and getting this error: 

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 535, in run_
    return self.run()
  File "/home/rafael/.config/sublime-text-3/Packages/FileZilla SFTP Import/SublimeZilla.py", line 24, in run
    self.quick_panel()
  File "/home/rafael/.config/sublime-text-3/Packages/FileZilla SFTP Import/SublimeZilla.py", line 27, in quick_panel
    server_names = self.get_server_names()
  File "/home/rafael/.config/sublime-text-3/Packages/FileZilla SFTP Import/SublimeZilla.py", line 166, in get_server_names
    self.servers = self.get_server_entries()
  File "/home/rafael/.config/sublime-text-3/Packages/FileZilla SFTP Import/SublimeZilla.py", line 220, in get_server_entries
    PassValTmp = base64.b64decode(PassVal).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 1: invalid start byte

**Comment by rfrancorj** [comment]
I fixed this by changing the line 220 to:
PassValTmp = base64.b64decode(PassVal).decode('utf-8', 'replace')

**Comment by ment4list** [comment]
Sorry for never getting back to you! I'm closing this. Thanks for the fix! :)
