### ISSUE TITLE
utf-8 ( non ascii ) characters in passwords not working

### ISSUE THREAD

**Issue by radist** [ment4list/SublimeZilla#20]
```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 797, in run_
    return self.run()
  File "/home/radist/.config/sublime-text-3/Packages/FileZilla SFTP Import/SublimeZilla.py", line 24, in run
    self.quick_panel()
  File "/home/radist/.config/sublime-text-3/Packages/FileZilla SFTP Import/SublimeZilla.py", line 27, in quick_panel
    server_names = self.get_server_names()
  File "/home/radist/.config/sublime-text-3/Packages/FileZilla SFTP Import/SublimeZilla.py", line 166, in get_server_names
    self.servers = self.get_server_entries()
  File "/home/radist/.config/sublime-text-3/Packages/FileZilla SFTP Import/SublimeZilla.py", line 220, in get_server_entries
    PassValTmp = base64.b64decode(PassVal).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 0: invalid continuation byte
```

**Comment by ment4list** [comment]
Thanks for the report!
Unfortunately, I'm not really sure how to handle this.. Could you perhaps give a test case so I can try replicate the issue?
Basically, which character(s) did you try that produced the above error?
