### ISSUE TITLE
Unable to run SublimeZilla

### ISSUE THREAD

**Issue by rpandrews** [ment4list/SublimeZilla#23]
I am unable to open SublimeZilla with "ctrl+alt+z" or by clicking "SublimeZilla" in the Tools menu.

Below is the error that is showing in the Sublime Text 3 console:

```
Unable` to open /C/Users/[UserName]/AppData/Roaming/Sublime Text 3/Packages/Default/Default (Windows).sublime-keymap
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1052, in run_
    return self.run()
  File "C:\Users\[UserName]\AppData\Roaming\Sublime Text 3\Packages\FileZilla SFTP Import\SublimeZilla.py", line 28, in run
    self.quick_panel()
  File "C:\Users\[UserName]\AppData\Roaming\Sublime Text 3\Packages\FileZilla SFTP Import\SublimeZilla.py", line 31, in quick_panel
    server_names = self.get_server_names()
  File "C:\Users\[UserName]\AppData\Roaming\Sublime Text 3\Packages\FileZilla SFTP Import\SublimeZilla.py", line 178, in get_server_names
    self.servers = self.get_server_entries()
  File "C:\Users\[UserName]\AppData\Roaming\Sublime Text 3\Packages\FileZilla SFTP Import\SublimeZilla.py", line 258, in get_server_entries
    if RemoteDir[0].firstChild is not None:
IndexError: list index out of range
```

I am running the latest version of both Sublime Text 3 (3.2.2) and FileZilla (3.47.1).

Any ideas?

Thanks.

**Comment by ment4list** [comment]
Hey

This isn't really being maintained anymore as I don't use it often.

> IndexError: list index out of range

Are you sure the Filezilla XML file has entries in it?

**Comment by rpandrews** [comment]
Thanks for your reply.

My XML file has 401 entries. My colleague is also having the same issue :-(
